#!/usr/bin/env python3
"""Generate the Ghostty theme and lazygit colours from nvim/lua/palette.lua.

Neovim reads the palette directly. Ghostty and lazygit cannot, so this writes
their files instead of leaving three copies of the same hexes to drift apart.

    ./scripts/sync-theme.py            write the files
    ./scripts/sync-theme.py --check    exit 1 if they are out of date
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PALETTE_LUA = ROOT / "nvim" / "lua" / "palette.lua"
GHOSTTY_THEME = ROOT / "ghostty" / "themes" / "oxocarbon-punch"
LAZYGIT_CONFIG = ROOT / "lazygit" / "config.yml"

HEADER = "# Generated by scripts/sync-theme.py from nvim/lua/palette.lua.\n# Edit the palette and re-run the script; changes here are overwritten.\n"


def load_palette() -> dict[str, str]:
    text = PALETTE_LUA.read_text()
    pairs = re.findall(r'^\s*(\w+)\s*=\s*"(#[0-9a-fA-F]{6})"', text, re.MULTILINE)
    if not pairs:
        sys.exit(f"no colours found in {PALETTE_LUA}")
    return dict(pairs)


def ghostty(p: dict[str, str]) -> str:
    # ANSI 0-7 normal, 8-15 bright. Ghostty wants palette entries with the hash.
    ansi = [
        p["bg"], p["red"], p["green"], p["yellow"],
        p["blue"], p["purple"], p["cyan"], p["white"],
        p["dim"], p["bright_red"], p["bright_green"], p["bright_yellow"],
        p["bright_blue"], p["bright_purple"], p["bright_cyan"], p["bright_white"],
    ]
    lines = [
        HEADER,
        "# Oxocarbon Punch: IBM Carbon tokens, warm anchors, matched to Neovim.\n",
        f"background = {p['bg'].lstrip('#')}",
        f"foreground = {p['fg'].lstrip('#')}",
        f"cursor-color = {p['yellow'].lstrip('#')}",
        f"selection-background = {p['sel'].lstrip('#')}",
        f"selection-foreground = {p['fg'].lstrip('#')}",
        "",
    ]
    lines += [f"palette = {i}={c}" for i, c in enumerate(ansi)]
    return "\n".join(lines) + "\n"


def lazygit(p: dict[str, str]) -> str:
    return f"""{HEADER}# Colours match the Neovim theme: yellow is the accent, red marks unstaged work.
gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor: ["{p['yellow']}", bold]
    inactiveBorderColor: ["{p['dim']}"]
    optionsTextColor: ["{p['blue']}"]
    selectedLineBgColor: ["{p['line']}"]
    selectedRangeBgColor: ["{p['line']}"]
    cherryPickedCommitBgColor: ["{p['sel']}"]
    cherryPickedCommitFgColor: ["{p['yellow']}"]
    unstagedChangesColor: ["{p['red']}"]
    defaultFgColor: ["{p['fg']}"]
    searchingActiveBorderColor: ["{p['orange']}"]
  authorColorDefault: "{p['purple']}"
git:
  paging:
    # delta syntax-highlights the diff so review reads like the editor, not a
    # flat red/green wall. --paging=never lets lazygit own scrolling; single
    # column keeps line-by-line staging (Space in the diff view) working.
    colorArg: always
    pager: delta --dark --paging=never
os:
  editPreset: "nvim"
"""


def main() -> int:
    p = load_palette()
    targets = [(GHOSTTY_THEME, ghostty(p)), (LAZYGIT_CONFIG, lazygit(p))]
    check = "--check" in sys.argv
    stale = False

    for path, content in targets:
        current = path.read_text() if path.exists() else None
        if current == content:
            print(f"ok      {path.relative_to(ROOT)}")
            continue
        stale = True
        if check:
            print(f"STALE   {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            print(f"wrote   {path.relative_to(ROOT)}")

    if check and stale:
        print("\nout of date: run ./scripts/sync-theme.py")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
